from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import requests

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.helpers import (
    SUMMARY_COMMENT_MARKER,
    create_issue_comment,
    dump_json,
    github_token_from_env,
    list_issue_comments,
    load_json,
    update_issue_comment,
    write_text,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render and optionally post a summary comment for a repo review run."
    )
    parser.add_argument("--repo", required=True, help="owner/name GitHub repository identifier.")
    parser.add_argument("--findings", required=True, help="Normalized findings JSON path.")
    parser.add_argument("--dedupe-report", required=True, help="Dedupe report JSON path.")
    parser.add_argument("--created-issues", required=True, help="Created issues JSON path.")
    parser.add_argument("--reopened-issues", required=True, help="Reopened issues JSON path.")
    parser.add_argument("--review-mode", required=True, help="Configured review mode.")
    parser.add_argument(
        "--comment-mode",
        required=True,
        choices=["off", "summary"],
        help="Whether to post a GitHub comment.",
    )
    parser.add_argument(
        "--comment-issue-number",
        required=False,
        default="",
        help="Issue number to host the summary comment.",
    )
    parser.add_argument(
        "--summary-output",
        required=True,
        help="Rendered markdown summary output path.",
    )
    parser.add_argument("--result-output", required=True, help="Comment result JSON output path.")
    return parser.parse_args()


def summarize_top_findings(findings_payload: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for finding in findings_payload.get("findings", [])[:5]:
        lines.append(
            "- "
            f"**{finding['title']}** "
            f"(severity: `{finding['severity']}`, confidence: `{finding['confidence']:.2f}`)"
        )
    return lines


def render_summary_comment(
    *,
    repo: str,
    review_mode: str,
    findings_payload: dict[str, Any],
    dedupe_report: dict[str, Any],
    created_issues: dict[str, Any],
    reopened_issues: dict[str, Any],
) -> str:
    findings_count = len(findings_payload.get("findings", []))
    duplicate_open_count = sum(
        1
        for item in dedupe_report.get("findings", [])
        if item.get("reason") == "duplicate_open_issue"
    )
    created_count = int(created_issues.get("created_count", 0))
    reopened_count = int(reopened_issues.get("reopened_count", 0))

    lines = [
        SUMMARY_COMMENT_MARKER,
        "# Automated Repository Review",
        "",
        f"- Repository: `{repo}`",
        f"- Run mode: `{review_mode}`",
        f"- Findings count: `{findings_count}`",
        "",
        "## Issue actions",
        f"- Skipped as duplicate open issues: `{duplicate_open_count}`",
        f"- Reopened issues: `{reopened_count}`",
        f"- Newly created issues: `{created_count}`",
        "",
        "## Top findings",
    ]
    lines.extend(
        summarize_top_findings(findings_payload) or ["- No findings met the current filters."]
    )
    lines.extend(
        [
            "",
            "## Artifacts",
            "- See the workflow artifacts for the full JSON payloads and markdown report.",
            "",
            "_This comment was generated by the automated repository review workflow._",
            "",
        ]
    )
    return "\n".join(lines)


def post_or_update_comment(
    *,
    repo: str,
    issue_number: int,
    body: str,
    session: requests.Session | None = None,
    token: str | None = None,
) -> dict[str, Any]:
    auth_token = token or github_token_from_env()
    comments = list_issue_comments(
        repo,
        issue_number=issue_number,
        token=auth_token,
        session=session,
    )
    existing = next(
        (comment for comment in comments if SUMMARY_COMMENT_MARKER in str(comment.get("body", ""))),
        None,
    )
    if existing:
        response = update_issue_comment(
            repo,
            comment_id=int(existing["id"]),
            token=auth_token,
            body=body,
            session=session,
        )
        action = "updated"
    else:
        response = create_issue_comment(
            repo,
            issue_number=issue_number,
            token=auth_token,
            body=body,
            session=session,
        )
        action = "created"
    return {
        "posted": True,
        "action": action,
        "comment_id": response.get("id"),
        "comment_url": response.get("html_url"),
        "comment_issue_number": issue_number,
    }


def build_skipped_result(*, issue_number: int | None, reason: str) -> dict[str, Any]:
    return {
        "posted": False,
        "action": "skipped",
        "comment_id": None,
        "comment_url": None,
        "comment_issue_number": issue_number,
        "reason": reason,
    }


def main() -> None:
    args = parse_args()
    findings_payload = load_json(Path(args.findings))
    dedupe_report = load_json(Path(args.dedupe_report))
    created_issues = load_json(Path(args.created_issues))
    reopened_issues = load_json(Path(args.reopened_issues))

    summary = render_summary_comment(
        repo=args.repo,
        review_mode=args.review_mode,
        findings_payload=findings_payload,
        dedupe_report=dedupe_report,
        created_issues=created_issues,
        reopened_issues=reopened_issues,
    )
    write_text(Path(args.summary_output), summary)

    issue_number = int(args.comment_issue_number) if args.comment_issue_number.strip() else None
    if args.comment_mode == "off":
        result = build_skipped_result(issue_number=issue_number, reason="comment_mode_off")
    elif issue_number is None:
        result = build_skipped_result(
            issue_number=None,
            reason="comment_issue_number_not_configured",
        )
    else:
        with requests.Session() as session:
            result = post_or_update_comment(
                repo=args.repo,
                issue_number=issue_number,
                body=summary,
                session=session,
            )

    dump_json(Path(args.result_output), result)


if __name__ == "__main__":
    main()
